apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dev-client
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "20"
spec:
  project: default

  source:
    repoURL: https://github.com/denismironiuk/helmchart-gitops
    targetRevision: dev
    path: dev/client
    helm:
      valueFiles:
        - values.yaml

  destination:
    server: https://kubernetes.default.svc
    namespace: dev-client

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
