apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: cert-issuer
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
spec:
  project: default
  source:
    repoURL: https://github.com/denismironiuk/test-nginx.git
    path: issuer
    targetRevision: main
  destination:
    server: https://kubernetes.default.svc
    namespace: cert-manager

  syncPolicy:
    automated:
      prune: true
      selfHeal: true
